//
//  CommentModel.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

//This model is used for comment system.
@objcMembers
class CommentModel: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _commentKey: String?
    var _commentDate: NSNumber?
    var _commentedBy: String?
    var _context: String?
    
    class func dynamoDBTableName() -> String {

        return "notes-mobilehub-1131310125-CommentModel"
    }
    
    class func hashKeyAttribute() -> String {

        return "_commentKey"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_commentDate"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_commentKey" : "commentKey",
               "_commentDate" : "commentDate",
               "_commentedBy" : "commentedBy",
               "_context" : "context",
        ]
    }
}
