//
//  LeaderBoardModel.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers

//This is the model for the leader board
class LeaderBoardModel: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _key: String?
    var _userId: String?
    var _point: String?
    var _submittedArray: Set<String>?
    var _userName: String?

    
    class func dynamoDBTableName() -> String {

        return "notes-mobilehub-1131310125-LeaderBoardModel"
    }
    
    class func hashKeyAttribute() -> String {

        return "_key"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_key" : "Key",
               "_userId" : "userId",
               "_point" : "point",
               "_submittedArray" : "submittedArray",
               "_userName" : "userName",
        ]
    }
}


var KeyForUser = "LeaderBoard" //used as partition key
var userInformationPool: [LeaderBoardModel] = []//store all user information
var submitArray: Set<String> = [] // check the answers the user has submitted
var exist = false //Used to determine if the app should create new informatin for the user
var newPoint = 0 //store the point of the logged in user
var LoggedInUser = LeaderBoardModel()//store all information about the logged in user
var advanceGroup: [String] = []//store users who gain points
var checkGroup: [LeaderBoardModel] = []//store the last userinformationpool
