//
//  Question.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

//This is the model for the question model
@objcMembers
class Question: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _subject: String?
    var _creationDate: NSNumber?
    var _answeredByArray: Set<String>?
    var _askedBy: String?
    var _description: String?
    var _imageKey: Set<String>?
    var _pageNum: NSNumber?
    var _questionNum: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "notes-mobilehub-1131310125-Question"
    }
    
    class func hashKeyAttribute() -> String {

        return "_subject"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_creationDate"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_subject" : "subject",
               "_creationDate" : "creationDate",
               "_answeredByArray" : "answeredByArray",
               "_askedBy" : "askedBy",
               "_description" : "description",
               "_imageKey" : "imageKey",
               "_pageNum" : "pageNum",
               "_questionNum" : "questionNum",
        ]
    }
}
var questionArray: [Question] = []
var test: [Question] = []
var selectedSubject = String()
var grade9Math: [Question] = []
var grade10Math: [Question] = []
var grade11Functions: [Question] = []
var grade12AdFunc: [Question] = []
var grade12DM: [Question] = []
var grade12Cal: [Question] = []
var grade11Phy: [Question] = []
var grade12Phy: [Question] = []
var grade11Che: [Question] = []
var grade12Che: [Question] = []
var grade11Bio: [Question] = []
var grade12Bio: [Question] = []
var specificSub = String()
var selectedQuestion = Question()
var shownImage = UIImage()
var name = String()
var key = String()
